// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Order struct {
	OrderID         int32
	UserID          int32
	StoreID         int32
	TotalAmount     float64
	Status          string
	DeliveryAddress string
	OrderDate       sql.NullTime
}

type OrderItem struct {
	OrderItemID int32
	OrderID     int32
	ProductID   int32
	Quantity    int32
	UnitPrice   float64
	TotalPrice  float64
}

type Product struct {
	ProductID   int32
	Name        string
	Description sql.NullString
	Price       float64
	Sku         string
	Category    sql.NullString
	CreatedAt   sql.NullTime
}

type Store struct {
	StoreID   int32
	Name      string
	Address   string
	Phone     sql.NullString
	CreatedAt sql.NullTime
}

type StoreInventory struct {
	InventoryID int32
	StoreID     int32
	ProductID   int32
	Quantity    int32
	LastUpdated sql.NullTime
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Phone     sql.NullString
	CreatedAt sql.NullTime
}
